/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.action.light

fun main() {
    App().start()
}

class App {

    val repo = "llschall/rgb-ribbon"

    fun start() {
        val token = ConfigLoader().getToken()
        val restRequest = RestRequest(repo, token)
        restRequest.send()
    }
}
