/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.continuous.light

import org.llschall.continuous.light.request.ConfigLoader
import org.llschall.continuous.light.request.RestRequest
import org.llschall.continuous.light.ribbon.Ribbon

fun main() {
    App().start()
}

class App {

    val greeting = "Welcome to the action light app."

    val user = "llschall"

    fun start() {
        println(greeting)

        val token = ConfigLoader().getToken()
        val restRequest = RestRequest(token)

        println("Fetching all repositories for user: $user")
        val repos = restRequest.getAllUserRepos(user)

        if (repos.isEmpty()) {
            System.err.println("No repositories found for user $user")
        } else {
            println("Found ${repos.size} repositories. Checking pull requests...")
            restRequest.send(repos)
        }

        val ribbon = Ribbon()
        ribbon.start()
    }
}
