/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.continuous.light

import org.llschall.continuous.light.request.ConfigLoader
import org.llschall.continuous.light.request.RestRequest
import org.llschall.continuous.light.ribbon.Ribbon
import java.awt.SystemTray
import java.awt.TrayIcon
import java.io.File
import javax.imageio.ImageIO

fun main() {
    App().start()
}

class App {

    val greeting = "Welcome to the continuous light app."

    val user = "llschall"

    fun start() {
        println(greeting)

        displayTrayIcon()

        val token = ConfigLoader().getToken()
        val restRequest = RestRequest(token)

        println("Fetching all repositories for user: $user")
        val repos = restRequest.getAllUserRepos(user)

        if (repos.isEmpty()) {
            System.err.println("No repositories found for user $user")
            return
        }

        println("Found ${repos.size} repositories:")

        // print all repositories
        for (repo in repos) {
            println("# Repository: $repo")
        }

        val ribbon = Ribbon()
        ribbon.start()

        for (i in 0..999_999) {
            val list = restRequest.send(repos)
            println("Found: ${list.size}")
            ribbon.update(list)
            Thread.sleep(5_000)
        }
    }

    fun displayTrayIcon() {
        if (!SystemTray.isSupported()) {
            System.err.println("System tray not supported");
            return
        }
        val image = ImageIO.read(File("src/main/resources/tray.png"))
        val tray = SystemTray.getSystemTray()
        val trayIcon = TrayIcon(image, "Continuous Light App")
        trayIcon.setImageAutoSize(true)
        tray.add(trayIcon)

        trayIcon.displayMessage(
            "Application started",
            "The app is now running in the background.",
            TrayIcon.MessageType.INFO
        )

    }
}
