/*
 * This source file was generated by the Gradle 'init' task
 */
package org.llschall.continuous.light

import org.llschall.continuous.light.request.ConfigLoader
import org.llschall.continuous.light.request.RestRequest
import org.llschall.continuous.light.ribbon.Ribbon

fun main() {
    App().start()
}

class App {

    val greeting = "Welcome to the action light app."

    val repo = "llschall/continuous-light"

    fun start() {
        println(greeting)

        val token = ConfigLoader().getToken()
        val restRequest = RestRequest(repo, token)
        restRequest.send()

        val ribbon = Ribbon()
        ribbon.start()
    }
}
